WITH RECURSIVE CTE AS
	(SELECT EMPLOYEE,
			MANAGER,
			ROW_NUMBER() OVER () AS X
		FROM COMPANY
		WHERE MANAGER =
				(SELECT EMPLOYEE
					FROM COMPANY
					WHERE MANAGER IS NULL )
		UNION ALL SELECT D.EMPLOYEE,
			D.MANAGER, X
		FROM CTE C
		JOIN COMPANY D ON C.EMPLOYEE = D.MANAGER)
SELECT CONCAT('team',

								X) AS TEAMS,
	STRING_AGG(MANAGER,

		',') AS MEMBERS
FROM
	(SELECT MANAGER, X
		FROM CTE
		UNION SELECT EMPLOYEE, X
		FROM CTE)Y
GROUP BY X
ORDER BY X;